//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public int DiscountID { get; set; }
        public int ProductID { get; set; }
        public decimal DiscountPercentage { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
