//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipments()
        {
            this.ShipmentDetails = new HashSet<ShipmentDetails>();
        }
    
        public int ShipmentID { get; set; }
        public int SupplierID { get; set; }
        public int EmployeeID { get; set; }
        public string TotalCost { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentDetails> ShipmentDetails { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
