//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetails
    {
        public int ShipmentDetailID { get; set; }
        public int ShipmentID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
